version: "3.8"

services:
  dondothat-server:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: dondothat-server
    ports:
      - "8080:8080"
    networks:
      - backend

  llm-server:
    build:
      context: ./llm-server
      dockerfile: Dockerfile
    container_name: llm-server
    env_file:
      - ./llm-server/.env
    ports:
      - "8000:8000"
    networks:
      - backend

networks:
  backend:
    driver: bridge