version: "3.8"

services:
  dondothat-server:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: dondothat-server
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysql-server
      - DB_PORT=3306
      - DB_NAME=dondothat
      - DB_USER=root
      - DB_PASSWORD=dondothat1234
    networks:
      - backend
    depends_on:
      - mysql-server

  llm-server:
    build:
      context: ./llm-server
      dockerfile: Dockerfile
    container_name: llm-server
    env_file:
      - ./llm-server/.env
    ports:
      - "8000:8000"
    networks:
      - backend

  mysql-server:
    image: mysql:8.0
    container_name: mysql-server
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=dondothat1234
      - MYSQL_DATABASE=dondothat
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mysql-data:
