# JDBC ??
jdbc.driver=net.sf.log4jdbc.sql.jdbcapi.DriverSpy

# EC2 MySQL ?? ??
DB_HOST=54.208.50.238
DB_PORT=3306
DB_NAME=dondothat
DB_USER=root
DB_PASSWORD=dondothat1234

# MySQL ?? ??
mysql.options=?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8

# Mail Configuration
SPRING_MAIL_HOST=smtp.gmail.com
SPRING_MAIL_PORT=587
SPRING_MAIL_USERNAME=hoonssac.dev@gmail.com
SPRING_MAIL_PASSWORD=ucgb gyyn qfup hhjb
SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true
SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=true

# OAuth2 ??
GOOGLE_CLIENT_ID=1019163246284-3m1e5qackut44qmuto10ne7lcldid5f9.apps.googleusercontent.com
GOOGLE_CLIENT_SECRET=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
NAVER_CLIENT_ID=X25DywQFSJq0ha8ZJFG0
NAVER_CLIENT_SECRET=xzLB_L3hTC
BASE_URL=http://dondothat.duckdns.org:8080
JWT_SECRET=dondothat-project-super-secret-key-for-jwt-authentication-2025

# Codef ??
CODEF_CLIENT_ID=12345
CODEF_CLIENT_SECRET=12345
CODEF_PUBLIC_KEY=12345

# AES ??
AES_SECRET_KEY=xkT5FcGBP/0zeq4EFfoElA5BvTAVyBtgwIT36crweUs=
